# Utiliser une image PHP officielle
FROM php:8.2-cli

# Copier les fichiers de votre projet dans le conteneur
COPY . /var/www/html

# Exposer le port 8080
EXPOSE 8080

# Démarrer le serveur PHP intégré
CMD ["php", "-S", "0.0.0.0:8080", "-t", "/var/www/html"]
